spring.application.name=bd
#conexõ com postgreSQL #
spring.datasource.url=jdbc:postgresql://localhost:5432/produtosdb-db
spring.datasource.username=postgres
spring.datasource.password=postgres
# JPA -Hibernate #
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



